"use client";
/* eslint-disable @next/next/no-img-element */

import { ChangeEvent, useEffect, useMemo, useState } from "react";

type Flag = { label: string; phrase: string; weight: number };
type Result = { score: number; label: string; flags: Flag[]; explanation: string; steps: string[] };
const samples = [
  { title: "KYC fraud", text: "Your KYC expires today. Update immediately to avoid account suspension. Click https://bit.ly/verify-kyc now." },
  { title: "Fake job", text: "Congratulations! You have been selected for a work-from-home job. Pay ₹499 registration fee now to confirm your seat." },
  { title: "UPI request", text: "I am from your bank. Please share the OTP to verify your account and avoid your account being blocked." }
];
const rules: Array<{ label: string; regex: RegExp; weight: number }> = [
  { label: "Urgency pressure", regex: /today|immediately|urgent|now|last chance|expire/i, weight: 17 },
  { label: "OTP or PIN request", regex: /\b(otp|pin|cvv|password)\b/i, weight: 31 },
  { label: "Account threat", regex: /account.{0,25}(block|suspend|freeze)|kyc.{0,20}(expire|update)/i, weight: 20 },
  { label: "Payment request", regex: /pay.{0,20}(fee|₹|rs\.?|inr)|registration fee|upi/i, weight: 17 },
  { label: "Impersonation", regex: /from your bank|bank employee|customer care|police/i, weight: 18 },
  { label: "Suspicious link", regex: /(bit\.ly|tinyurl|https?:\/\/)/i, weight: 12 },
  { label: "Unrealistic offer", regex: /congratulations|selected|work.from.home|reward|prize|guaranteed/i, weight: 13 },
  { label: "App installation", regex: /install.{0,20}app|download.{0,20}app|screen share/i, weight: 23 }
];
function analyze(text: string): Result {
  const flags = rules.flatMap((rule) => { const match = text.match(rule.regex); return match ? [{ label: rule.label, phrase: match[0], weight: rule.weight }] : []; });
  const score = Math.min(98, flags.reduce((total, f) => total + f.weight, 0) + (flags.length > 2 ? 8 : 0));
  const label = score >= 60 ? "High risk" : score >= 35 ? "Suspicious" : score >= 15 ? "Caution" : "Safe";
  const steps = score >= 35 ? ["Do not reply, click the link, or make a payment.", "Never share your OTP, PIN, password, or card details.", "Verify independently using the official app or number.", "Tell someone you trust before taking any action."] : ["Pause before responding or sharing personal information.", "Verify the sender through an official channel.", "Keep your OTP, PIN, and passwords private."];
  return { score, label, flags, explanation: flags.length ? `This message uses ${flags.map(f => f.label.toLowerCase()).join(", ")}. Scammers use these cues to rush you before you can verify the request.` : "No common scam patterns were found. Still verify unexpected requests independently.", steps };
}
const translations = { en: { checker: "Check a suspicious message", paste: "Paste message", upload: "Upload screenshot", link: "Check link", analyze: "Analyze safely", demo: "Demo rule-based analysis", report: "Report this scam", simple: "Explain simply", community: "Community safety" }, hi: { checker: "संदिग्ध संदेश जाँचें", paste: "संदेश लिखें", upload: "स्क्रीनशॉट अपलोड करें", link: "लिंक जाँचें", analyze: "सुरक्षित रूप से जाँचें", demo: "डेमो नियम-आधारित जाँच", report: "इस धोखाधड़ी की रिपोर्ट करें", simple: "आसान भाषा में समझाएँ", community: "कम्युनिटी सुरक्षा" } };

export default function Home() {
  const [mode, setMode] = useState<"message" | "upload" | "link">("message"); const [text, setText] = useState(""); const [preview, setPreview] = useState(""); const [result, setResult] = useState<Result | null>(null); const [loading, setLoading] = useState(false); const [lang, setLang] = useState<"en" | "hi">("en"); const [simple, setSimple] = useState(false); const [reported, setReported] = useState(false); const [filter, setFilter] = useState("All");
  const t = translations[lang];
  useEffect(() => { const hash = window.location.hash; if (hash === "checker") document.getElementById("checker")?.scrollIntoView(); }, []);
  const demoReports = useMemo(() => [ ["Job", "Fake work-from-home fee", "New Delhi", "12 min ago"], ["KYC/Bank", "KYC expiry link", "Pune", "34 min ago"], ["UPI/Payment", "Collect request impersonation", "Bengaluru", "1 hr ago"], ["Delivery", "Redelivery charge link", "Mumbai", "2 hrs ago"], ["Investment", "Guaranteed returns group", "Jaipur", "3 hrs ago"] ], []);
  function run() { if (!text.trim() && !preview) return; setLoading(true); setResult(null); setTimeout(() => { setResult(analyze(text || "Screenshot submitted for review")); setLoading(false); }, 750); }
  function upload(e: ChangeEvent<HTMLInputElement>) { const f = e.target.files?.[0]; if (!f) return; setPreview(URL.createObjectURL(f)); setText("Screenshot uploaded — visual/OCR analysis is ready for an optional AI integration."); }
  function report() { const reports = JSON.parse(localStorage.getItem("sachetReports") || "[]"); localStorage.setItem("sachetReports", JSON.stringify([...reports, { createdAt: new Date().toISOString(), score: result?.score }])); setReported(true); }
  function share() { const msg = `Sachet flagged this message as ${result?.label} (${result?.score}/100). Please pause and verify before taking action.`; window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`, "_blank", "noopener,noreferrer"); }
  return <main>
    <nav><a className="brand" href="#top"><span>◈</span> sachet</a><div className="navlinks"><a href="#how">How it works</a><a href="#community">{t.community}</a><a href="#privacy">Privacy</a><button className="language" onClick={() => setLang(lang === "en" ? "hi" : "en")}>{lang === "en" ? "हिंदी" : "EN"}</button></div></nav>
    <section id="top" className="hero"><div className="eyebrow">YOUR DIGITAL SAFETY COMPANION</div><h1>Pause. Check.<br/><em>Stay Safe.</em></h1><p>Spot scam signals before they cost you money. Paste a message, scan a link, or upload a screenshot for a clear, private safety check.</p><a className="primary" href="#checker">Check a suspicious message <b>→</b></a><div className="hero-note"><span className="shield">✓</span> Your checks stay on your device in this demo</div><div className="orb orb-one"/><div className="orb orb-two"/></section>
    <section className="usecases"><div><span>01</span><h3>Fake job offers</h3><p>Spot up-front fees and too-good-to-be-true promises.</p></div><div><span>02</span><h3>KYC & bank scams</h3><p>Know when urgency is being used to trick you.</p></div><div><span>03</span><h3>UPI payment fraud</h3><p>Catch unsafe payment requests before you approve.</p></div></section>
    <section id="checker" className="checker"><div className="section-intro"><div className="eyebrow">THE SAFETY CHECK</div><h2>{t.checker}</h2><p>Take a moment. A safer decision begins with a quick check.</p></div><div className="check-card"><div className="tabs">{(["message", "upload", "link"] as const).map(x => <button key={x} className={mode === x ? "active" : ""} onClick={() => { setMode(x); setResult(null); }}>{x === "message" ? t.paste : x === "upload" ? t.upload : t.link}</button>)}</div>{mode === "message" && <><label htmlFor="message">Paste the message you received</label><textarea id="message" value={text} onChange={e => setText(e.target.value)} placeholder="Paste a WhatsApp, SMS, email, or DM here…"/><div className="samples">Try an example: {samples.map(s => <button key={s.title} onClick={() => { setText(s.text); setResult(null); }}>{s.title}</button>)}</div></>}{mode === "link" && <><label htmlFor="link">Enter the suspicious link</label><input id="link" value={text} onChange={e => setText(e.target.value)} placeholder="https://example.com/claim"/></>}{mode === "upload" && <><label className="dropzone" htmlFor="file">{preview ? <img src={preview} alt="Uploaded screenshot preview"/> : <><strong>Drop your screenshot here</strong><span>PNG, JPG, or WEBP · screenshot remains local</span></>}<input id="file" type="file" accept="image/*" onChange={upload}/></label></>}<button className="analyze" onClick={run} disabled={loading || (!text.trim() && !preview)}>{loading ? "Checking signals…" : <>✦ {t.analyze}</>}</button><p className="disclaimer">◌ {t.demo} · No message is sent to a server</p></div></section>
    {result && <section className="results"><div className="result-top"><div><div className="eyebrow">YOUR SAFETY RESULT</div><h2>{result.label}</h2><p>{simple ? "This message is asking you to act fast or share something private. Stop, do not pay, and check with the real company yourself." : result.explanation}</p></div><div className={`score ${result.score >= 60 ? "danger" : result.score >= 35 ? "warn" : "safe"}`}><b>{result.score}</b><span>/100 risk</span></div></div><div className="result-grid"><div className="flags"><h3>Signals we found</h3>{result.flags.length ? result.flags.map(f => <div className="flag" key={f.label}><span>!</span><div><b>{f.label}</b><small>“{f.phrase}”</small></div></div>) : <p className="muted">No common red flags detected.</p>}</div><div className="steps"><h3>What to do now</h3>{result.steps.map((s, i) => <div className="step" key={s}><span>{i + 1}</span>{s}</div>)}</div></div><div className="result-actions"><button onClick={() => setSimple(!simple)} className="secondary">◉ {t.simple}</button><button onClick={share} className="secondary">↗ Share with trusted contact</button><button onClick={report} className="report">{reported ? "✓ Report saved anonymously" : t.report}</button></div></section>}
    <section id="how" className="how"><div className="eyebrow">BUILT FOR CALM, NOT PANIC</div><h2>Safety advice that makes sense<br/>when it matters most.</h2><div className="how-grid"><div><span>01</span><h3>Share what looks off</h3><p>Paste text, enter a link, or upload a screenshot.</p></div><div><span>02</span><h3>See the signals</h3><p>We explain specific cues scammers use to pressure you.</p></div><div><span>03</span><h3>Choose the safe next step</h3><p>Clear, human advice—before you click, pay, or reply.</p></div></div></section>
    <section id="community" className="community"><div><div className="eyebrow">COMMUNITY SAFETY PULSE</div><h2>Spot patterns.<br/><em>Protect each other.</em></h2><p>Anonymous reports help reveal what scams are circulating. This view uses sample demo data only.</p><div className="filters">{["All", "Job", "KYC/Bank", "UPI/Payment", "Delivery", "Investment"].map(f => <button key={f} className={filter === f ? "selected" : ""} onClick={() => setFilter(f)}>{f}</button>)}</div></div><div className="report-list">{demoReports.filter(r => filter === "All" || r[0] === filter).map((r) => <div className="community-item" key={r[1]}><div className="pin">⌖</div><div><span>{r[0]}</span><h3>{r[1]}</h3><p>{r[2]} · {r[3]}</p></div><b>›</b></div>)}</div></section>
    <section id="privacy" className="privacy"><div className="privacy-icon">◈</div><div><div className="eyebrow">PRIVACY FIRST</div><h2>Your concern is personal.<br/>Your safety check should be too.</h2></div><p>Sachet is designed to help you recognize common scam patterns. This demo keeps checks in your browser and never publishes your content. It provides safety guidance—not legal, banking, or emergency services advice.</p></section>
    <footer><a className="brand" href="#top"><span>◈</span> sachet</a><p>© 2026 Sachet. Built to make every click a little safer.</p><a href="#top">Back to top ↑</a></footer>
  </main>;
}
